{
  parserClass="com.kaylerrenslow.plugin.lang.header.parser.HeaderParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="SQF"
  psiImplClassSuffix="Impl"
  psiPackage="com.kaylerrenslow.plugin.lang.header.psi"
  psiImplPackage="com.kaylerrenslow.plugin.lang.header.psi.impl" //comment out the import statement in the HeaderTypes class if the impl package isn't used

  elementTypeHolderClass="com.kaylerrenslow.plugin.lang.header.psi.HeaderTypes"
  elementTypeClass="com.kaylerrenslow.plugin.lang.header.psi.HeaderElementType"
  tokenTypeClass="com.kaylerrenslow.plugin.lang.header.psi.HeaderTokenType"
}
// @formatter:off
headerFile ::= item_*


private item_ ::= COMMENT | statement_ | WHITE_SPACE | LINE_TERMINATOR | BAD_CHARACTER

private statement_ ::= (assignment_ | classDeclaration_ | preprocessor_) SEMICOLON

private assignment_ ::= basicAssignment_ | arrayAssignment_
private basicAssignment_ ::= IDENTIFIER EQ value_
private arrayAssignment_ ::= IDENTIFIER BRACKET_PAIR EQ array_

private array_ ::= LBRACE RBRACE | LBRACE value_ (COMMA value_)* RBRACE

private value_ ::= STRING_LITERAL | NUMBER_LITERAL | CONSTANT | IDENTIFIER

private classDeclaration_ ::= CLASS IDENTIFIER (
                                                LBRACE RBRACE
                                                | LINE_TERMINATOR LBRACE LINE_TERMINATOR (item_)* RBRACE
                                               )?

private preprocessor_ ::= COMMA COLON PREPROCESS_HASH//TODO