{
  parserClass="com.kaylerrenslow.plugin.parser.SQFParser_NoSyntax"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="SQF"
  psiImplClassSuffix="Impl"
  psiPackage="com.kaylerrenslow.plugin.psiNoSyntax"
  psiImplPackage="com.kaylerrenslow.plugin.lang.sqf.psi.implNoSyntax"

  elementTypeHolderClass="com.kaylerrenslow.plugin.lang.sqf.psi.SQFTypes"
  elementTypeClass="com.kaylerrenslow.plugin.lang.sqf.psi.SQFElementType"
  tokenTypeClass="com.kaylerrenslow.plugin.lang.sqf.psi.SQFTokenType"
}
// @formatter:off
sqfFile ::= token_*

private token_ ::= WHITE_SPACE
                 /*identifiers*/
                 | LOCAL_VAR
                 | IDENTIFIER

                 /*comments*/
                 | COMMENT
                 | COMMENT_KEYWORD

                 /*literals*/
                 | STRING_LITERAL
                 | INTEGER_LITERAL
                 | DEC_LITERAL

                 /*commands*/
                 | COMMAND

                 /*values*/
                 | TRUE
                 | FALSE
                 | NIL
                 | TYPE_NULL

                 /*lang constants*/
                 | CONFIG
                 | LANG_CONSTANT
                 | NAMESPACE

                 /*control structure keywords*/
                 | PRIVATE
                 | GOTO
                 | BREAK
                 | BREAK_TO
                 | BREAK_OUT
                 | CONTINUE
                 | SCOPE_NAME
                 | IF
                 | THEN
                 | ELSE
                 | EXIT_WITH
                 | SWITCH
                 | DO
                 | CASE
                 | DEFAULT
                 | WHILE
                 | FOR
                 | FOR_EACH
                 | TO
                 | STEP
                 | FROM
                 | WAIT_UNTIL
                 | ASSERT
                 | TRY
                 | CATCH
                 | THROW
                 | WITH

                 /*operators and other symbols*/
                 | LBRACE
                 | RBRACE
                 | LBRACKET
                 | RBRACKET
                 | LPAREN
                 | RPAREN
                 | SEMICOLON
                 | EXCL
                 | NOT
                 | EQ
                 | AMPAMP
                 | AND
                 | BARBAR
                 | OR
                 | EQEQ
                 | NE
                 | LT
                 | GT
                 | LE
                 | GE
                 | PLUS
                 | MINUS
                 | ASTERISK
                 | CARET
                 | PERC
                 | MOD
                 | FSLASH
                 | GTGT
                 | COMMA
                 | COLON
                 | QUEST

                 | BAD_CHARACTER


// @formatter:on